#!/usr/bin/env bash
BACK=`pwd`
cd "$(dirname "$0")"
ssh wifi3r 'opkg update ; opkg install rsync'
./push overlay/upper/etc/opkg/installed
./push overlay/upper/srv/tftp/arch/
./push overlay/upper/usr/bin/statistics
./push overlay/upper/usr/bin/listuserpackages
./push overlay/upper/etc/init.d/dnsmasq
ssh wifi3r 'opkg install $(cat /etc/opkg/installed | sed -e "s/^\(.*\) - .*$/\1/")'
./push overlay/upper/usr/lib/qos/generate.sh
./push overlay/upper/etc/adblock/adblock.sources.gz
cd "$BACK"
