#!/usr/bin/env bash
BACK=`pwd`
cd "$(dirname "$0")"
ssh wifi3r 'opkg update ; opkg install rsync'
./push overlay/upper/etc/opkg/installed
ssh wifi3r 'mkdir -p /overlay/upper/srv/tftp/arch/'
./push overlay/upper/srv/tftp/arch/
./push overlay/upper/usr/bin/statistics
./push overlay/upper/usr/bin/listuserpackages
./push overlay/upper/etc/hotplug.d/iface/60-qos
ssh wifi3r 'opkg install $(cat /etc/opkg/installed)'
ssh wifi3r 'rm /etc/hotplug.d/iface/10-qos'
./push overlay/upper/usr/lib/qos/generate.sh
./push overlay/upper/etc/adblock/adblock.sources.gz
cd "$BACK"
