#!/bin/sh
source /usr/sbin/helper.sh

logger -t $(basename $0) "$1"

case "$1" in
    eth3)
        iptables -t nat -I PREROUTING -i br0 -p udp --dport 53 -j DNAT --to $(nvram get lan_ipaddr)
        ;;
esac
